[workspace]
resolver = "2"
members = [
    "crates/unstructured-cli",
    "crates/unstructured-client",
]


[workspace.dependencies]
tokio = { version = "1.38.1", features = ["full"] }

[workspace.package]
license = "Apache-2.0"
version = "0.1.1"
